### ISSUE TITLE
IncompatibleClassChangeError when using junitplatform. 

### ISSUE THREAD

**Issue by hhariri** [JetBrains/spek#128]
$ gradle mybatis:test
:mybatis:compileKotlin UP-TO-DATE
:mybatis:compileJava UP-TO-DATE
:mybatis:processResources UP-TO-DATE
:mybatis:classes UP-TO-DATE
:mybatis:compileTestKotlin
:mybatis:compileTestJava UP-TO-DATE
:mybatis:processTestResources UP-TO-DATE
:mybatis:testClasses UP-TO-DATE
:mybatis:junitPlatformTest
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
:mybatis:junitPlatformTest FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':mybatis:junitPlatformTest'.
  
  > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

See project:

https://github.com/xmlking/cloud-native-apps/tree/master/mybatis

gradle mybatis:test

**Comment by Adambl4** [comment]
Is there any workaround for this?

**Comment by Adambl4** [comment]
Reflection library of 1.1 and 1.0.4(which Spek used) are not compatible. 
Solution: 
1. Build Spek using 1.1
2. Ensure that there is no another version of Kotlin in classpath
```
configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
             if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion %kotlinVersion%
            }
        }
    }
}

**Comment by raniejade** [comment]
Thanks @Adambl4 for looking into this. I'm concerned that something similar may happen every time a new version comes out. Not a fan of building the same thing for different Kotlin versions.

**Comment by raniejade** [comment]
To avoid this issue, make sure that Spek uses your version of Kotlin. You can enforce this using any build tool. Closing this issue now.
