### ISSUE TITLE
unable to mock using mockito in spek tests

### ISSUE THREAD

**Issue by Nejat** [JetBrains/spek#132]
i'm not sure if i set things up correctly, i'm new to kotlin and gradle

I've included the Spek to recreate the issue, the exception output and the `bundle.gradle` file

The same exact test using JUnit, with Mockito_Kotlin or just pure Mockito works as expected, so I do not believe it's the test itself

Does Mockito work with Spek? If so, how do I get it working.?

I rather not have two separate testing frameworks, as I really prefer BDD over TDD, and you've done a great job with Spek, thanks for the advice

```kotlin
package bug.mocking.spek

import com.winterbe.expekt.should
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.describe
import org.jetbrains.spek.api.dsl.given
import org.jetbrains.spek.api.dsl.it
import org.mockito.Mockito.*

class MockingTests : Spek({

    describe("mocking with mockito in spek") {

        given("mocking Iterable<T> and Iterator<T>") {

            it("should iterate mocked values") {
                
                val mockedIterable: Iterable<*> = Mockito.mock(Iterable::class.java)
                val mockedIterator: Iterator<*> = Mockito.mock(Iterator::class.java)

                `when`(mockedIterator.hasNext()).thenReturn(true, true, true, true, false)
                `when`(mockedIterator.next()).thenReturn(0, 1, 2, 3)

                `when`(mockedIterable.iterator()).thenReturn(mockedIterator)

                val actual   = mockedIterable.joinToString(", ")
                val expected = "0, 1, 2, 3"

                actual.should.be.equal(expected)
            }
        }
    }
})
```

```error
Oct 28, 2016 8:31:17 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek, junit-jupiter]

null
java.lang.ExceptionInInitializerError
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1632)
	at org.mockito.Mockito.mock(Mockito.java:1545)
	at org.nexivo.testing.sandbox.jupiter.MockingTests$1$1$1$1.invoke(MockingTests.kt:33)
	at org.nexivo.testing.sandbox.jupiter.MockingTests$1$1$1$1.invoke(MockingTests.kt:10)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:110)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:83)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:81)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:88)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:88)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:88)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:88)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:124)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.jetbrains.spek.tooling.execution.SpekTestRunner.run(SpekTestRunner.kt:89)
	at org.jetbrains.spek.tooling.execution.MainKt.main(Main.kt:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@42e99e4a
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:82)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:36)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:13)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:12)
	... 37 more
Caused by: java.lang.IllegalStateException: Error during attachment using: ByteBuddyAgent.AttachmentProvider.Compound{attachmentProviders=[ByteBuddyAgent.AttachmentProvider.ForJigsawVm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForJ9Vm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JVM_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JDK_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.MACINTOSH]}
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:314)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:280)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:248)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:234)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:77)
	... 40 more
Caused by: java.io.IOException: Access is denied
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at net.bytebuddy.agent.ByteBuddyAgent$AgentProvider$ForByteBuddyAgent.resolve(ByteBuddyAgent.java:863)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:305)
	... 50 more
```

`bundle.gradle`
```groovy
group "bug.mocking.spek"
version "1.0-SNAPSHOT"

buildscript {
    ext.expekt_version         = "0.5.0"
    ext.kotlin_version         = "1.0.4"
    ext.junit_version          = "5.0.0-M2"
    ext.junit_platform_version = "1.0.0-M2"
    ext.mockito_kt_version     = "0.9.0"
    ext.mockito_version        = "2.2.9"
    ext.spek_version           = "1.0.89"

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.junit.platform:junit-platform-gradle-plugin:$junit_platform_version"
    }
}

apply plugin: "kotlin"
apply plugin: "org.junit.platform.gradle.plugin"

junitPlatform {
    engines {
        include "spek", "jupiter"
    }
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    testCompile "org.junit.platform:junit-platform-runner:$junit_platform_version"
    testCompile "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testCompile "org.jetbrains.spek:spek-api:$spek_version"
    testCompile "com.winterbe:expekt:$expekt_version"
    testCompile "com.nhaarman:mockito-kotlin:$mockito_kt_version"
    testCompile "org.mockito:mockito-core:$mockito_version"

    testRuntime "org.jetbrains.spek:spek-junit-platform-engine:$spek_version"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}
```

**Comment by hhariri** [comment]
I just tried your exact example and it worked both using the Spek Test Runner as Gradle. 

Btw, if you're using the given/on/it style then you don't really need describe. Or if you're using describe and executing tests on it, then you don't need given.

**Comment by Nejat** [comment]
Thank you, I see the problem now.  

This is only happening with the Spek plugin for IntelliJ.  I had the latest one available in the Plugin repository v0.2.5.

It does not happen when I use a JUnit configuration and as you pointed out Gradle.

What is the Spek Test Runner?

**Comment by hhariri** [comment]
Sorry I mean the Spek plugin. It seems to be working here with the latest release.

**Comment by Nejat** [comment]
What's the version you're using?

**Comment by hhariri** [comment]
Hmm. I was using 0.2.4 and it was working. Upgraded to latest and having issues. @raniejade ?

**Comment by Nejat** [comment]
If it helps, I installed 0.2.4 and it's still not working. It maybe possible that it's a dependency issue?

**Comment by hhariri** [comment]
Are you getting the same issue still with the upgrade?

**Comment by ayooladedeji** [comment]
Hey, any fix for this?
