### ISSUE TITLE
Unable to run after upgrade

### ISSUE THREAD

**Issue by sblundy** [JetBrains/spek#133]
After upgrading to 2016.3, I am unable to run a Spek run configuration. I press run and nothing would happen. IntelliJ's exception dialog just popped up. The tests have worked previously and run when I execute the gradle test task. Deleting the config and running anew resulted in a different exception.

### Environment

Spek plugin: 0.2.5
Kotlin version: 1.0.3

> IntelliJ IDEA 2016.3
> Build #IU-163.7743.44, built on November 17, 2016
> ...
> JRE: 1.8.0_112-release-408-b2 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### Exception when I ran an existing run config
<pre>org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
java.lang.IllegalAccessError: org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
	at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
	at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
	at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
	at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
	at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</pre>

### Exception on new run config
<pre>null
java.lang.IllegalAccessError
	at sun.misc.Unsafe.throwIllegalAccessError(Unsafe.java:1142)
	at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
	at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
	at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
	at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
	at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</pre>

**Comment by sblundy** [comment]
Sorry, wrong project
