### ISSUE TITLE
compatibility issues with surefire plugin

### ISSUE THREAD

**Issue by jakubgwozdz** [JetBrains/spek#138]
There is a problem with versioning (or at least with lack of documentation on it).
In my pom.xml, I have this versions specified:
```xml
    <properties>
        <kotlin.version>1.0.5-2</kotlin.version>
        <spek.version>1.1.19</spek.version>
        <surefire.version>2.19.1</surefire.version>
        <junit.platform.version>1.0.0-M2</junit.platform.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
```
(1.1.19 is taken from <repository> and <pluginRepository> https://dl.bintray.com/jetbrains/spek - as it is not yet on central repo)

And this runs and launches tests, but when there is a test failure, instead of reporting it, the build stops with 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project xmlscan: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed. NullPointerException -> [Help
 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project xmlscan: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2
.19.1:test failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
...
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugin.surefire.report.DefaultReporterFactory.printTestFailures(DefaultReporterFactory.java:346)
        at org.apache.maven.plugin.surefire.report.DefaultReporterFactory.runCompleted(DefaultReporterFactory.java:137)
...
```

I assume this is because the newest, "2.19.1", is not correct version of plugin for spek-junit-platform-engine, but then - what would be, given that I decided to use JUnit5, at least M2?

It would be great to have all the required versions for all components listed in documentation

**Comment by jakubgwozdz** [comment]
Sort of solved, when I added @RunWith(JUnitPlatform::class) to each of test classes and removed plugin dependencies as documented on http://junit.org/junit5/docs/current/user-guide/#running-tests-build

**Comment by raniejade** [comment]
Have you checked http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven? Not well versed with maven, but I'll try my best to help.

**Comment by jakubgwozdz** [comment]
@raniejade - yeah, I did it first, exactly as it said on junit5 docs and with that I had errors. 
When I moved back to @RunWith it started working.

**Comment by raniejade** [comment]
Okay, let me know if you have further problems.
