### ISSUE TITLE
Kotlin Gradle Script Problems

### ISSUE THREAD

**Issue by CoreyKaylor** [JetBrains/spek#139]
I'm new to kotlin, spek, and gradle so I'm sure I've done something wonky for this not to work. I followed the instructions in the documentation to get the build.gradle.kts setup for spek but I keep getting an error that says Extension of type 'EnginesExtension' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, SelectorsExtension_Decorated, FiltersExtension_Decorated]. I'm not sure how to resolve this problem. Here is what I have going on for my setup. Any help would be appreciated.

IntelliJ can compile and run the tests just fine for spek.
IntelliJ tooling works for my build.gradle.kts file.
gradle --version = 3.2

``` kotlin
import org.gradle.api.plugins.ExtensionAware
import org.junit.platform.gradle.plugin.EnginesExtension
import org.junit.platform.gradle.plugin.JUnitPlatformExtension


buildscript {
    val kotlinVersion = "1.0.5"
    val junitGradlePluginVersion = "1.0.0-M3"

    repositories {
        gradleScriptKotlin()
    }

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
        classpath("org.junit.platform:junit-platform-gradle-plugin:${junitGradlePluginVersion}")
    }
}

apply {
    plugin("kotlin")
    plugin("org.junit.platform.gradle.plugin")
}

repositories {
    gradleScriptKotlin()
}

dependencies {
    compile(kotlinModule("stdlib"))
    testCompile("org.jetbrains.spek:spek:1.0.89")
    testRuntime("org.jetbrains.spek:spek-junit-platform-engine:1.0.89")
}

configure<JUnitPlatformExtension> {
    engines {
        include("spek")
    }
}

fun JUnitPlatformExtension.engines(setup: EnginesExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(EnginesExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an instance of ExtensionAware")
    }
}
```

**Comment by CoreyKaylor** [comment]
My problem doesn't appear to be isolated to kotlin scripts. Here is my gradle script that has the same problem.

``` groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.0.5'
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3'
    }
}

apply plugin: 'kotlin'
apply plugin: 'org.junit.platform.gradle.plugin'

dependencies {
    testCompile 'org.jetbrains.spek:spek:1.0.89'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:1.0.89'
}

junitPlatform {
    engines {
        include 'spek'
    }
}
```

**Comment by raniejade** [comment]
They changed the structure in `1.0.0-M3`, so it should be:

```gradle
junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}
```

**Comment by CoreyKaylor** [comment]
Got a little bit further. New error now. Sorry if this is trivial stuff.

```
Dec 04, 2016 8:06:31 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek]
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/platform/engine/discovery/ClasspathSelector
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:48)
        at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:36)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:109)
```

Current gradle script

```groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.0.5'
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3'
    }
}

apply plugin: 'kotlin'
apply plugin: 'org.junit.platform.gradle.plugin'

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:1.0.5"
    testCompile "org.jetbrains.kotlin:kotlin-test:1.0.5"
    testCompile 'org.jetbrains.spek:spek-api:1.0.89'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:1.0.89'
}

repositories {
    mavenCentral()
}

junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}
```

Current spec is just the calculator example from the docs.

``` kotlin
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.describe
import org.jetbrains.spek.api.dsl.it
import kotlin.test.assertEquals

class SimpleSpec: Spek({
    describe("a calculator") {
        val calculator = SampleCalculator()

        it("should return the result of adding the first number to the second number") {
            val sum = calculator.sum(2, 4)
            assertEquals(6, sum)
        }

        it("should return the result of subtracting the second number from the first number") {
            val subtract = calculator.subtract(4, 2)
            assertEquals(2, 0)
        }
    }
})

class SampleCalculator {
    fun sum(num1: Int, num2: Int) = num1 + num2
    fun subtract(num1: Int, num2: Int) = num1 - num2
}
```

**Comment by raniejade** [comment]
Oops sorry, you have to explicitly set the platformVersion to `1.0.0-M2`. Several classes used by spek were renamed from that version. I've got that fix but I'm having problems deploying a new version, just stick with that version for now.

```gradle
junitPlatform {
    platformVersion '1.0.0-M2'
    filters {
        engines {
            include 'spek'
        }
    }
}
```

**Comment by CoreyKaylor** [comment]
Getting closer, now everything compiles but fails to find my spec.

```
:junitPlatformTest
Dec 04, 2016 8:47:34 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek]

Test run finished after 44 ms
[         0 tests found      ]
[         0 tests skipped    ]
[         0 tests started    ]
[         0 tests aborted    ]
[         0 tests successful ]
[         0 tests failed     ]
[         0 containers failed]


BUILD SUCCESSFUL
```

**Comment by CoreyKaylor** [comment]
Okay, I figured that part out. I didn't realize the default test discovery convention needed to have the files inside package folders. I think I'm good to go now. Thanks for the help.

**Comment by raniejade** [comment]
Just released `v1.1.0-beta2` it's in bintray can you try that out? Should now be compatible with JUnit Platform `1.0.0-M3`.

**Comment by CoreyKaylor** [comment]
Again new to gradle, but I took a guess that the bintray repository is jcenter() in the gradle? I wasn't able to locate it under that one. If not, can you point me to the right repository url?

**Comment by CoreyKaylor** [comment]
Actually, maybe I'm partly wrong. I believe it found the spek-api, but not the spek-junit-platform-engine.

**Comment by raniejade** [comment]
Yep, it's in `jcenter`. Both artifacts should be there (`spek-api` and `spek-junit-platform-engine`), can you paste your update build script here?

**Comment by CoreyKaylor** [comment]
Sure, here's the output.

```
Could not resolve all dependencies for configuration ':testRuntime'.
> Could not find org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta2.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/jetbrains/spek/spek-junit-platform-engine/1.1.0-beta2/spek-junit-platform-engine-1.1.0-beta2.pom
      https://repo1.maven.org/maven2/org/jetbrains/spek/spek-junit-platform-engine/1.1.0-beta2/spek-junit-platform-engine-1.1.0-beta2.jar
      https://jcenter.bintray.com/org/jetbrains/spek/spek-junit-platform-engine/1.1.0-beta2/spek-junit-platform-engine-1.1.0-beta2.pom
      https://jcenter.bintray.com/org/jetbrains/spek/spek-junit-platform-engine/1.1.0-beta2/spek-junit-platform-engine-1.1.0-beta2.jar
  Required by:
      project :
```

Here's the gradle script.

```groovy
buildscript {
    ext.kotlin_version = '1.0.3'
    ext.spek_version = '1.1.0-beta2'
    ext.junit_runner_version = '1.0.0-M3'

    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.junit.platform:junit-platform-gradle-plugin:$junit_runner_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'org.junit.platform.gradle.plugin'

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile "org.jetbrains.spek:spek-api:$spek_version"
    testCompile "org.junit.platform:junit-platform-runner:$junit_runner_version"
    testRuntime "org.jetbrains.spek:spek-junit-platform-engine:$spek_version"
}

repositories {
    mavenCentral()
    jcenter()
}

junitPlatform {
    platformVersion junit_runner_version
    filters {
        engines {
            include 'spek'
        }
    }
}
```

**Comment by raniejade** [comment]
I think I know the problem, will let you know when we fix it.

**Comment by raniejade** [comment]
So we are experiencing problem with `jcenter()`, to use the new version. Please add the following configuration.

```gradle
repositories {
    maven { url "https://dl.bintray.com/jetbrains/spek" }
}
```
