### ISSUE TITLE
Exceptions inside coroutines not failing test

### ISSUE THREAD

**Issue by osipxd** [JetBrains/spek#290]
I have problem when trying to test methods that use coroutines.

**Code:**
```kotlin
class CoroutinesSpec : Spek({
    it("should fail when we use [runBlocking]") {
        runBlocking { failWithThreadName() }
        println("I mustn't see this message")
    }

    it("should fail when we use [runBlocking] with [run] inside") {
        runBlocking {
            run(CommonPool) { failWithThreadName() }
        }
        println("I mustn't see this message")
    }

    it("should fail when we use [runBlocking] inside [run]") {
        runBlocking {
            run(CommonPool) {
                runBlocking { failWithThreadName() }
            }
        }
        println("I mustn't see this message")
    }

    it("should fail when we use [runBlocking] with [launch] inside") {
        runBlocking {
            launch(Unconfined) { failWithThreadName() }.join()
        }
        println("I mustn't see this message")
    }

    it("should fail when we use [runBlocking] inside [launch]") {
        runBlocking {
            launch(Unconfined) {
                runBlocking { failWithThreadName() }
            }.join()
        }
        println("I mustn't see this message")
    }
})

private fun failWithThreadName() {
    fail("in thread ${Thread.currentThread().name}")
}
```
**Result of tests:**
All should fail, but when I using launch it isn't fails
![image](https://user-images.githubusercontent.com/3684355/31852146-473ff856-b67b-11e7-9532-2f060126c28c.png)

**Output:**
```
failed: it should fail when we use [runBlocking]
- java.lang.AssertionError: in thread main

failed: it should fail when we use [runBlocking] with [run] inside
- java.lang.AssertionError: in thread ForkJoinPool.commonPool-worker-1

failed: it should fail when we use [runBlocking] inside [run]
- java.lang.AssertionError: in thread ForkJoinPool.commonPool-worker-1

success: it should fail when we use [runBlocking] with [launch] inside
- Exception in thread "main" java.lang.AssertionError: in thread main
- I mustn't see this message

success: it should fail when we use [runBlocking] inside [launch]
- Exception in thread "main" java.lang.AssertionError: in thread main
- I mustn't see this message
```

**Stacktraces:**
When using `run`:
```
java.lang.AssertionError: in thread main

	at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:12)
	at kotlin.test.AssertionsKt__AssertionsKt.fail(Assertions.kt:85)
	at kotlin.test.AssertionsKt.fail(Unknown Source)
	at com.example.spek.CoroutinesSpecKt.failWithThreadName(CoroutinesSpec.kt:46)
	at com.example.spek.CoroutinesSpecKt.access$failWithThreadName(CoroutinesSpec.kt:1)
	at com.example.spek.CoroutinesSpec$1$1$1.doResume(CoroutinesSpec.kt:13)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:122)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:232)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:153)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:146)
	at com.example.spek.CoroutinesSpec$1$1.invoke(CoroutinesSpec.kt:13)
	at com.example.spek.CoroutinesSpec$1$1.invoke(CoroutinesSpec.kt:11)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:102)
```
When using `launch`:
```
Exception in thread "main" java.lang.AssertionError: in thread main
	at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:12)
	at kotlin.test.AssertionsKt__AssertionsKt.fail(Assertions.kt:85)
	at kotlin.test.AssertionsKt.fail(Unknown Source)
	at com.example.spek.CoroutinesSpecKt.failWithThreadName(CoroutinesSpec.kt:46)
	at com.example.spek.CoroutinesSpecKt.access$failWithThreadName(CoroutinesSpec.kt:1)
	at com.example.spek.CoroutinesSpec$1$4$1$1.doResume(CoroutinesSpec.kt:32)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.CoroutineDispatcherKt.resumeCancellable(CoroutineDispatcher.kt:230)
	at kotlinx.coroutines.experimental.CancellableKt.startCoroutineCancellable(Cancellable.kt:34)
	at kotlinx.coroutines.experimental.CoroutineStart.invoke(CoroutineStart.kt:113)
	at kotlinx.coroutines.experimental.BuildersKt.launch(Builders.kt:63)
	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Builders.kt:55)
	at com.example.spek.CoroutinesSpec$1$4$1.doResume(CoroutinesSpec.kt:32)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:122)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:232)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:153)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:146)
	at com.example.spek.CoroutinesSpec$1$4.invoke(CoroutinesSpec.kt:31)
	at com.example.spek.CoroutinesSpec$1$4.invoke(CoroutinesSpec.kt:11)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:102)
```

**Comment by jcornaz** [comment]
@osipxd, I guess you found out why since then. But here is the answer:

* This problem is not related to Spek at all. JUnit would have had the same behavior
* `launch` is a fire-and-forget. `join` never throw, even if the underling coroutine failed. This is by design. If one wants to have a `join` that throw in case of failure of the underling coroutine, then he has to use `async` and `await` instead.
* This problem is however elegantly solved since structured concurrency (`CoroutineScope`) introduced in kotlinx.coroutines 0.26. Now, with your code, the `launch` would start a child coroutine of the `runBlocking` one. Which means:
  * No need to join, `runBlocking` will block until all its children are completed (with or without success)
  * `runBlocking` will throw the exception if any of its children failed.

I short: Using the latest version of kotlinx.coroutines solves the problem ;-)
