### ISSUE TITLE
Executing all specs in package fails if one has include of an anonymous object

### ISSUE THREAD

**Issue by robstoll** [JetBrains/spek#321]
Consider the following situation:
in package `a` there is only one file with:
````
object TestA : Spek({
    include(object : Spek({
        it("test 1"){}

    }) {})
})
````
Executing it alone (in intellij) works fine. Executing all tests in package `a` fails:
```
Nov 04, 2017 12:09:23 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Call is not yet supported for this function: public constructor `TestA$1$1`() defined in ch.tutteli.atrium.a.`TestA$1$1`[DeserializedClassConstructorDescriptor@7a69b07] (member = null)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:89)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:34)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
	at org.jetbrains.spek.engine.SpekTestEngine$defaultInstanceFactory$1.create(SpekTestEngine.kt:44)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:113)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:74)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
````

Then I have package b which also just has one file:
````
class Test: Spek({
    include(TestA)
    it("test 2"){
    }
})
````
Executing it alone works but also executing all test in package b. I hope this extra information helps to track down the bug

**Comment by raniejade** [comment]
Kotlin compiles the inner object as a separate class, so when you're running a test for a package Spek picks it up and tries to create an instance of it - as a fix we need to check if the class is `anonymous` or not. Thanks for the report!

**Comment by cldfzn** [comment]
Is this the same thing occurring for my attempt at shared tests (where ConfigurationSpec is an abstract class with a SpecBody):

`itBehavesLike(object : ConfigurationSpec() {})`

Same exception as above. I worked around it using an extension method SpecBody.assume() that checks if the subject is set and executes the SpecBody if so. Idea was taken from an older StackOverflow post.

**Comment by raniejade** [comment]
Closing, fixed in `2.x`.
