### ISSUE TITLE
Spek Idea Plugin crash

### ISSUE THREAD

**Issue by hoangtranwork** [JetBrains/spek#332]
I've seen random crash on this plugin, even when working on a pure Java project with another Kotlin/Spek project open side by side.

https://www.dropbox.com/s/d133q968mlwogdy/Screenshot%202017-11-17%2014.13.41.png?dl=0

The stacktrace in the Detail tab:
```
Argument for @NotNull parameter 'module' of com/intellij/openapi/roots/ModuleRootManager.getInstance must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'module' of com/intellij/openapi/roots/ModuleRootManager.getInstance must not be null
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java)
	at org.jetbrains.spek.idea.SpekRunConfigurationProducer.isConfigurationFromContext(SpekRunConfigurationProducer.kt:124)
	at org.jetbrains.spek.idea.SpekRunConfigurationProducer.isConfigurationFromContext(SpekRunConfigurationProducer.kt:25)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:210)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:229)
	at com.intellij.openapi.externalSystem.action.task.RunExternalSystemTaskAction.perform(RunExternalSystemTaskAction.java:52)
	at com.intellij.openapi.externalSystem.action.task.RunExternalSystemTaskAction.perform(RunExternalSystemTaskAction.java:36)
	at com.intellij.openapi.externalSystem.action.ExternalSystemNodeAction.actionPerformed(ExternalSystemNodeAction.java:65)
	at com.intellij.openapi.externalSystem.action.ExternalSystemActionUtil.executeAction(ExternalSystemActionUtil.java:56)
	at com.intellij.openapi.externalSystem.view.ExternalProjectsViewImpl.handleDoubleClickOrEnter(ExternalProjectsViewImpl.java:269)
	at com.intellij.openapi.externalSystem.view.ExternalSystemNode.handleDoubleClickOrEnter(ExternalSystemNode.java:400)
	at com.intellij.ui.treeStructure.SimpleTree.lambda$handleDoubleClickOrEnter$1(SimpleTree.java:399)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by raniejade** [comment]
This is fixed, but not released yet.
