### ISSUE TITLE
TypeCastException with Spek 0.5.4

### ISSUE THREAD

**Issue by Eternity-Yarr** [JetBrains/spek#355]
Here is the stack trace
```
org.jetbrains.spek.idea.SpekJvmConfigurationFactory@3ad3ea78 produced wrong type: null cannot be cast to non-null type org.jetbrains.kotlin.psi.KtNamedFunction
kotlin.TypeCastException: null cannot be cast to non-null type org.jetbrains.kotlin.psi.KtNamedFunction
	at org.jetbrains.spek.idea.SpekJvmUtils.extractPath(SpekJvmUtils.kt:123)
	at org.jetbrains.spek.idea.SpekJvmUtils.extractPath(SpekJvmUtils.kt:140)
	at org.jetbrains.spek.idea.SpekJvmUtils.extractPath$default(SpekJvmUtils.kt:118)
	at org.jetbrains.spek.idea.SpekJvmRunConfigurationProducer.setupConfigurationFromContext(SpekJvmRunConfigurationProducer.kt:85)
	at org.jetbrains.spek.idea.SpekJvmRunConfigurationProducer.setupConfigurationFromContext(SpekJvmRunConfigurationProducer.kt:25)
	at com.intellij.execution.actions.RunConfigurationProducer.createLightConfiguration(RunConfigurationProducer.java:255)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.a(ExecutorAction.kt:76)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.b(ExecutorAction.kt:62)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.access$getConfigurations(ExecutorAction.kt:45)
	at com.intellij.execution.lineMarker.ExecutorAction.a(ExecutorAction.kt:108)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:85)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:84)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.a(GutterIntentionAction.java:80)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.a(GutterIntentionAction.java:147)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.a(GutterIntentionAction.java:140)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.a(GutterIntentionAction.java:117)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:102)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:373)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:245)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by raniejade** [comment]
@Eternity-Yarr can you provide what IntelliJ version are you using? Also if you can provide the source file you are viewing when this happened.

**Comment by Eternity-Yarr** [comment]
Sorry, i couldn't recall what source file i was watching two weeks ago :(

![2018-01-31-142547_535x163_scrot](https://user-images.githubusercontent.com/3705333/35620611-b490eaf2-0692-11e8-917f-6ab3aab877eb.png)
