### ISSUE TITLE
shouldNotBeNull does not work

### ISSUE THREAD

**Issue by codeslubber** [JetBrains/spek#49]
Does the opposite:

    shouldNotBeNull(agentCommission)

Yields this result:

``` 
  java.lang.AssertionError: . Expected value to be null, but was: <Payout@326de728>.
    at kotlin.test.DefaultAsserter.fail(TestJVM.kt:79)
    at kotlin.test.Asserter$DefaultImpls.assertTrue(Test.kt:112)
    at kotlin.test.DefaultAsserter.assertTrue(TestJVM.kt:73)
    at kotlin.test.Asserter$DefaultImpls.assertNull(Test.kt:149)
```

Opposite of what is expressed.

**Comment by hhariri** [comment]
Should be fixed now.
