### ISSUE TITLE
Improve docs for android

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#507]
Some good feedback on the stuff that is missing.
> Has a complete step-by-step guide on how to get it to work in Android Studio. Spek has this doc, but it misses a few steps, like how do I run the tests? Which run configuration do I create in Android Studio? Do I just run a gradle task? Do I need the IDE plugin? Etc. The Android-JUnit5 readme doesn't help much either. Then when something doesn't work, I don't know if I did something wrong, or if that feature is just not supported (e.g. go-to-test on double-click from the test runner UI).
from https://www.reddit.com/r/Kotlin/comments/9m3j7v/i_think_that_minutest_radically_simplifies/e7bpud9

**Comment by StanislasGaitUp** [comment]
I am posting this here since I believe that the sample projects help to make Android easy to use. 
I did not manage to make the android sample work: 
After cloning the repo and having only one easy modif (updating to gradle 3.2.0), I have had this crash when starting the tests (same thing happened for the separate module and the current app).

```
Exception in thread "main" org.junit.platform.commons.util.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:55)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:66)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by raniejade** [comment]
@StanislasGaitUp is it this sample: https://github.com/spekframework/spek/tree/2.x/samples/android?

**Comment by StanislasGaitUp** [comment]
No it was this one, https://github.com/spekframework/spek-android-example I will look at this sample then

**Comment by StanislasGaitUp** [comment]
@raniejade I am facing the same problem with the sample code from https://github.com/spekframework/spek/tree/2.x/samples/android
I also had to update the gradle to 4.7 because Android Studio told me that Junit5 requires this version

**Comment by raniejade** [comment]
~Ooops, sorry. @StanislasGaitUp change this line ` testRuntimeOnly "org.spekframework.spek2:spek-runner-junit5:$spek_version"` to ` testImplementation "org.spekframework.spek2:spek-runner-junit5:$spek_version"`. I've updated the docs but forgot to update the samples.~ I was looking at an outdated branchm weird.

**Comment by raniejade** [comment]
Forgot to ask, how are you running it? command line (gradle)? or android studio?

**Comment by StanislasGaitUp** [comment]
I am using Android Studio, to run the tests I am right clicking on tests/org.spekframework.speksample, then clicking on "Run Specks in tests/org.spekframework.speksample" and then I get "Test framework quit unexpectedly. "

**Comment by StanislasGaitUp** [comment]
I don't know if it matters but I have Android Studio 3.2 with Spek plugin Version: 0.5.5-studio3.0

**Comment by raniejade** [comment]
You need the new plugin, search for `Spek Framework` in the plugin interface.

**Comment by StanislasGaitUp** [comment]
Well thank you ! It is working now ! I knew it was something stupid that I had done...
