### ISSUE TITLE
Error "Test framework quit unexpectedly" when running tests from a package that contains other packages

### ISSUE THREAD

**Issue by yaroslav-shlapak** [JetBrains/spek#543]
Environment:
Android Studio 3.3 RC 1Build #AI-182.5107.16.33.5138683, built on November 19, 2018
Spek plugin versoin: 2.0.0-rc.1.158+20181104T071551Z-IJ2018.2
    jacocoVersion = "0.8.2"
    spekVersion = "2.0.0-rc.1"
    androidTestRunnerVersion = "1.0.2"
    junitJupiterVersion = "5.3.1"
    junit5RunnerVersion = "0.2.2"
    junit5GradlePuginVersion = "1.3.1.1"
    kotlinTestVersion = "3.1.10"
    mockkVersion = "1.8.13.kotlin13"

Prerequirements: 
a package that contains other packages with unit tests.

Steps to reproduce
1. Right click on the package-> Run 'Spek tests ...'
2. "Instantiating tests... " is displayed in the Run tab
3. "Test framework quit unexpectedly" is displayed in the Run tab

Additional info:
When I uninstall Spek plugin, I'm able to run tests using JUnit from the same package
When Spek plugin is installed there are no errors when I run tests from the package containing test files without packages.

I suppose the reason for such behavior is IJ plugin. Is there AS 3.3 plugin?

I really enjoy writing tests with Spek, thank you!

**Comment by raniejade** [comment]
The plugin you pulled is for IntelliJ IDEA, let me try building the plugin for 3.3. Might take awhile, need to download over a gig of IDE data 😂

**Comment by yaroslav-shlapak** [comment]
I've just tried to run tests from a package with:
Android Studio 3.2.1 Build #AI-181.5540.7.32.5056338, built on October 9, 2018
Spek plugin versoin: 2.0.0-rc.1.158+20181104T071551Z-Studio3.2

same error

As a workaround, it is possible to run tests using Junit from the configuration:
![screenshot from 2018-11-30 12-19-37](https://user-images.githubusercontent.com/3373419/49283384-4552df00-f49a-11e8-9753-1f9a471d47c3.png)

**Comment by raniejade** [comment]
@yaroslav-shlapak that's weird. Can you share a project that reproduces your problem?

**Comment by yaroslav-shlapak** [comment]
Just created one: https://github.com/yaroslav-shlapak/TestSpekProject

**Comment by raniejade** [comment]
@yaroslav-shlapak can you try adding `testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"` to your dependencies? I suspect your pulling in an incompatible version of kotlin-reflect. Spek2 is built against kotlin `1.2.71`.

**Comment by yaroslav-shlapak** [comment]
I've added changes to the test project:

https://github.com/yaroslav-shlapak/TestSpekProject/commit/37381781ca9110cae9d718f8c069c3ed9f4d4b13?diff=unified
https://github.com/yaroslav-shlapak/TestSpekProject/commit/da4fd290783142fce60018710aef42a59c6db429?diff=unified

and got the same error. 

Might the AS Kotling plugin: 1.3.10-release-Studio3.2-1 be a culprit?

**Comment by raniejade** [comment]
@yaroslav-shlapak sorry, should be `testImplementatio"org.jetbrains.kotlin:kotlin-reflect:$kotlin_version`. hmmm, let me check.

**Comment by raniejade** [comment]
Can you try this build out? 
[2.0.0-rc.1.164+4297c4a-Studio3.2.zip](https://github.com/spekframework/spek/files/2633216/2.0.0-rc.1.164%2B4297c4a-Studio3.2.zip)

**Comment by yaroslav-shlapak** [comment]
Yes, it works. Is it possible to build the similar plugin for AS 3.3?

**Comment by raniejade** [comment]
@yaroslav-shlapak I published a build recently, were you able to test it out?

**Comment by yaroslav-shlapak** [comment]
The latest build of plugin doesn't work at all. I've got the error on Android Studio start up:
```
java.lang.NoClassDefFoundError: com/android/tools/idea/run/PreferGradleMake
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:278)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:274)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:243)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:147)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.spekframework.intellij.SpekAndroidConfigurationFactory.createTemplateConfiguration(SpekAndroidConfigurationFactory.kt:14)
	at com.intellij.execution.actions.RunConfigurationProducer.createLightConfiguration(RunConfigurationProducer.java:241)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.computeConfigurations(ExecutorAction.kt:61)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.getConfigurations(ExecutorAction.kt:46)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.access$getConfigurations(ExecutorAction.kt:31)
	at com.intellij.execution.lineMarker.ExecutorAction.getActionName(ExecutorAction.kt:94)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:71)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:84)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:256)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:199)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:350)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:110)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.invokePopup(EditorGutterComponentImpl.java:1875)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mousePressed(EditorGutterComponentImpl.java:1630)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.processMousePressed(EditorImpl.java:3763)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMousePressedCommand$0(EditorImpl.java:3629)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:3634)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:3565)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.run.PreferGradleMake PluginClassLoader[org.spekframework, 2.0.0-rc.1.170+fe27af0-Studio3.3] com.intellij.ide.plugins.cl.PluginClassLoader@7ea3cfa4
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 66 more
```
Spek plugin version Version: 2.0.0-rc.1.170+fe27af0-Studio3.3
Android Studio 3.3 RC 2
Build #AI-182.5107.16.33.5160847, built on December 4, 2018

Additional symptoms:
"Nothing here" when clicking on test play button near the Spek test/group
State of latest/saved tests in the configurations:
![screenshot from 2018-12-17 10-20-14](https://user-images.githubusercontent.com/3373419/50074766-975b6a80-01e5-11e9-9365-c6156ab0c738.png)

**Comment by yaroslav-shlapak** [comment]
2.0.0-rc.1.167+0914c41-IJ2018.2 works but with the issue reported at the top of this thread.

**Comment by raniejade** [comment]
@yaroslav-shlapak I think I found the issue, let me rebuild the plugin.

**Comment by raniejade** [comment]
Can you try this out? [2.0.0-rc.1.174+c371da5-Studio3.3.zip](https://github.com/spekframework/spek/files/2690020/2.0.0-rc.1.174%2Bc371da5-Studio3.3.zip)

🤞

**Comment by yaroslav-shlapak** [comment]
It works sometimes, but sometimes I push the play button near the test/group and then push run and nothing happens. Moreover, Alt+Enter keyboard shortcut stops to work with this plugin. There are no such issues with 2.0.0-rc.1.167+0914c41-IJ2018.2. Also, with 2.0.0-rc.1.174+c371da5-Studio3.3 when I try to run tests from a package there are no Spek runners to choose from the popup list menu, only JUnit.

**Comment by raniejade** [comment]
@yaroslav-shlapak Yep, known issues some are fixed in master.
