### ISSUE TITLE
[Plugin] Android Studio 3.2 play button "Nothing here"

### ISSUE THREAD

**Issue by 0mega** [JetBrains/spek#554]
Hi there,
Really like using Spek, great job with this framework!

I've seen several reports of the Spek plugin not running when clicking on the play button. Although some people report it's working for them, in my case, I tried several build of the plugin for AS 3.2 and it does not work.

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Spek Framework plugin version:  2.0.0-rc.1.169+2c45d6a-Studio3.2

I get the "Nothing here":
<img width="190" alt="screen shot 2018-12-20 at 17 47 54" src="https://user-images.githubusercontent.com/519615/50304622-fb00c480-047f-11e9-9654-8289ad19e7ad.png">

Besides that I can see that whenever I open a test file written with Spek, the IDE produces an exception:
```
org.jetbrains.kotlin.config.KotlinFacetSettings.getPlatform()Lorg/jetbrains/kotlin/platform/IdePlatform;
java.lang.NoSuchMethodError: org.jetbrains.kotlin.config.KotlinFacetSettings.getPlatform()Lorg/jetbrains/kotlin/platform/IdePlatform;
	at org.spekframework.intellij.SpekRunConfigurationProducer.setupConfigurationFromContext(SpekRunConfigurationProducer.kt:66)
	at org.spekframework.intellij.SpekRunConfigurationProducer.setupConfigurationFromContext(SpekRunConfigurationProducer.kt:19)
	at com.intellij.execution.actions.RunConfigurationProducer.createLightConfiguration(RunConfigurationProducer.java:246)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.computeConfigurations(ExecutorAction.kt:76)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.getConfigurations(ExecutorAction.kt:62)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.access$getConfigurations(ExecutorAction.kt:45)
	at com.intellij.execution.lineMarker.ExecutorAction.getActionName(ExecutorAction.kt:108)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:85)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:84)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.isAvailable(GutterIntentionAction.java:80)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:147)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:140)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:117)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:102)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:376)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:245)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Thanks

**Comment by raniejade** [comment]
Thanks for the report. What version of the kotlin plugin do you have installed?

**Comment by 0mega** [comment]
Kotlin plugin: 1.2.71-release-Studio3.2-1

**Comment by raniejade** [comment]
@0mega Upgrading to the kotlin 1.3 as plugin should fix your problem.

**Comment by 0mega** [comment]
Thank you @raniejade, it does work. 
To prevent this kind of question in the future, is there any reference doc that would point which version of AS works with which version of Spek Plugin and which version of Kotlin is required?
