### ISSUE TITLE
Using the gutter icon in IntelliJ may not run the tests.

### ISSUE THREAD

**Issue by jcornaz** [JetBrains/spek#568]
Given the following test:
```kotlin
import org.amshove.kluent.shouldBeFalse
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

class ExperimentSpec : Spek({
  describe("group") {
    it("should work") {
      true.shouldBeFalse()
    }
  }
})
```

Running from the gutter icon:
![image](https://user-images.githubusercontent.com/2535178/51172266-2aee8c80-18b3-11e9-854e-03559ce6e637.png)

Doesn't run any test:
![image](https://user-images.githubusercontent.com/2535178/51172277-35a92180-18b3-11e9-9dd8-8f37b6f92fe4.png)

But running all tests from IntelliJ contextual menu:
![image](https://user-images.githubusercontent.com/2535178/51172336-52ddf000-18b3-11e9-8caf-d019d072c370.png)

Runs the test as expected.
![image](https://user-images.githubusercontent.com/2535178/51172368-64bf9300-18b3-11e9-9545-823f0686d41c.png)

**Comment by raniejade** [comment]
Can you share the full stacktrace of the failure?

**Comment by jcornaz** [comment]
>Can you share the full stacktrace of the failure?

There is no point. The failure is the expected behavior. I want the test to fail.

The non-expected behavior is when no test run. And there isn't any stacktrace for that.

**Comment by raniejade** [comment]
It gives me a point to start the investigation, honestly I can't find a reason why it doesn't fail. Have you tried rerunning it again after doing `Run "All Tests"`?

**Comment by jcornaz** [comment]
>It gives me a point to start the investigation

Ok.
```
java.lang.AssertionError: Expected value to be false, but was true
	at org.junit.Assert.fail(Assert.java:88)
	at kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:168)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:178)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.AssertionsKt__AssertionsKt.assertFalse(Assertions.kt:43)
	at kotlin.test.AssertionsKt.assertFalse(Unknown Source)
	at org.amshove.kluent.internal.AssertionsKt.assertFalse(Assertions.kt:9)
	at org.amshove.kluent.BasicKt.shouldBeFalse(Basic.kt:44)
	at ExperimentSpec$1$1$1.invoke(ExperimentSpec.kt:8)
	at ExperimentSpec$1$1$1.invoke(ExperimentSpec.kt:5)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:92)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.AbstractRuntime.execute(SpekRuntime.kt:32)
	at org.spekframework.spek2.junit.SpekTestEngine.execute(SpekTestEngine.kt:55)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Just keep in mind that it is the *expected* exception.

>Have you tried rerunning it again after doing Run "All Tests"?

Yes. It doesn't help.

**Comment by jcornaz** [comment]
Using latest version of Spek plugin, I now have a stack-trace printed in the console:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.spekframework.spek2.runtime.execution.DiscoveryRequest.<init>(Lorg/spekframework/spek2/runtime/discovery/DiscoveryContext;Ljava/util/List;)V
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:18)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)
```

**Comment by raniejade** [comment]
@jcornaz the dev builds are not compatible with `2.0.0`, known issue: #631.

**Comment by jcornaz** [comment]
Given @raniejade comment: 
> the dev builds are not compatible with 2.0.0, known issue: #631 

And given that we never seen the problem again (and we write Spek tests every day)

I think we can close this issue.
