### ISSUE TITLE
Exception thrown running Spek test in Android Studio

### ISSUE THREAD

**Issue by boylenssen** [JetBrains/spek#648]
Running tests from command line is no problem, running them using the plugin seems to give issues.
using plugin 2.0.1-studio-3.3

I suddenly get this error:

Exception in thread "main" java.lang.NoSuchMethodError: org.spekframework.spek2.runtime.execution.DiscoveryRequest.<init>(Lorg/spekframework/spek2/runtime/discovery/DiscoveryContext;Ljava/util/List;)V
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:18)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)

Process finished with exit code 1

I tried it in my small test project, I have it attached.

[MyApplication.zip](https://github.com/spekframework/spek/files/2936531/MyApplication.zip)

**Comment by m-maillot** [comment]
Same for me:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.spekframework.spek2.runtime.execution.DiscoveryRequest.<init>(Lorg/spekframework/spek2/runtime/discovery/DiscoveryContext;Ljava/util/List;)V
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:18)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)
```

```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

Spek plugin: Version: 2.0.1-Studio3.3

**Comment by tinetti** [comment]
Same here...
```
IntelliJ IDEA 2018.3.5 (Community Edition)
Build #IC-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by raniejade** [comment]
Hey all! Apologies for the trouble there is an incompatibility issue noted in the release:

> Fixing #606 required making some incompatible changes between 2.0.1 runtime and 2.0.0 IJ plugin, please hold off from upgrading to 2.0.1 until the IJ plugin is available (it usually takes a few hours as JB needs to manually approve them first). If you have existing run configurations created using the 2.0.0 IJ plugin, you need to recreate them. Apologies for any inconvenience this has caused!

Two possible fixes:

1. If you are using `2.0.1` plugin please use `2.0.1` in your project.
2. If you have existing run configurations created using the 2.0.0 IJ plugin, you need to recreate them.

**Comment by boylenssen** [comment]
Ow thanks! I did update dependency to spek version 2.0.1 and now it works. Thanks for the fast response!

**Comment by raniejade** [comment]
Closing this, the only fix is using the same version in your project and the IDE plugin.
