### ISSUE TITLE
Discovery phase of SpekTestEngine fails for nested class inside Spek tests

### ISSUE THREAD

**Issue by KeithYokoma** [JetBrains/spek#654]
This is related to https://github.com/spekframework/spek/issues/642 but I still have a problem running tests with Spek `2.0.1` from CLI.

```kotlin

class SampleTest : Spek({
  class NestedClass {
    // ...
  }

  Feature("sample feature") {
    // Scenario, When, Then inside this block...
  }
})
```

This will produce the following output in standard error: it seems SpekTestEngine fails during discovery phase for getting `null` from KClass#qualifiedName.

```
Gradle Test Executor 1 STANDARD_ERROR
    org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    Warning: TestEngine with ID 'spek2' failed to discover tests
    java.lang.IllegalStateException: Required value was null.
        at org.spekframework.spek2.runtime.util.ClassUtil.extractPackageAndClassNames(ClassUtil.kt:7)
        at org.spekframework.spek2.runtime.scope.PathBuilder$Companion.from(Path.kt:99)
        at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:53)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by raniejade** [comment]
Please use `@Ignore`for the moment, the fix for #642 is scheduled for the `2.0.2` release.

**Comment by KeithYokoma** [comment]
`@Ignore` does not take effect since class selectors are built in [`SpekTestEngine`](https://github.com/spekframework/spek/blob/2.x/spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt#L50) and it doesn't care if a class is annotated with `@Ignore` or not.

```kotlin:SpekTestEngine.kt
class SpekTestEngine : TestEngine {

    // ...

    override fun discover(discoveryRequest: EngineDiscoveryRequest, uniqueId: UniqueId): TestDescriptor {

        // ...

        val classSelectors = discoveryRequest.getSelectorsByType(ClassSelector::class.java)
            .map {
                PathBuilder
                    .from(it.javaClass.kotlin) // this line fails according to the stack trace
                    .build()
            }
    }
}
```

I think we need to add some filters to check `@Ignore` annotation existence and the class is local or not before passing `KClass` object to `PathBuilder#from`.

**Comment by raniejade** [comment]
Re-opening as it is an issue with the JUnit 5 test engine.
