### ISSUE TITLE
Check plugin compatibility with IJ 2019.1

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#662]

**Comment by jcornaz** [comment]
*EDIT: Original content removed.*

*I Realized that my problem wasn't a compatibility problem between of IJ 2019.1 and Spek.*

*My problem was due to the fact that I had both `Spek` and [kotlintest](https://github.com/kotlintest/kotlintest) runners in my runtime classpath.*

*Sorry for the false positive.*

*Bottom line: Spek works like a Charm for me on Windows and IJ 2019.1*

**Comment by Lakedaemon** [comment]
I get one exception while running Spek2 in intellij 2019.1

Exception in thread "main" java.lang.NoSuchMethodError: org.spekframework.spek2.runtime.execution.DiscoveryRequest.<init>(Lorg/spekframework/spek2/runtime/discovery/DiscoveryContext;Ljava/util/List;)V
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:18)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)

**Comment by Lakedaemon** [comment]
Please note that I'm not using the bundled java runtime (because the damn intellij idea is just unable to make it switch to the bundled runtime though it has been pestering me with it for months).

If you tell me this is related, I'll try to fix that

**Comment by raniejade** [comment]
You need to make sure you have the same spek version for your project and the IJ plugin. `2.0.0` and `2.0.1` are not compatible.

**Comment by Lakedaemon** [comment]
thanks. It makes sense and It fixed the issue.

(Also, I finally fixed the damn java bundled problem but it had no impact).

I'll now happily resume using spek2 (I only use that, you see and I would have reverted back to idea 2018 if I could not make it work).
Many thanks :)
