### ISSUE TITLE
java.lang.AbstractMethodError: org.spekframework.spek2.runtime.Collector.getDefaultTimeout()J

### ISSUE THREAD

**Issue by vanniktech** [JetBrains/spek#683]
After updating from 2.0.2 to 2.0.3 I'm getting the following exception:

```
java.lang.AbstractMethodError: org.spekframework.spek2.runtime.Collector.getDefaultTimeout()J
	at org.spekframework.spek2.style.specification.Suite.it$default(specificationStyle.kt:39)
	at com.vanniktech.analytics.DelegateAnalyticsSpek$1$1.invoke(DelegateAnalyticsSpek.kt:17)
	at com.vanniktech.analytics.DelegateAnalyticsSpek$1$1.invoke(DelegateAnalyticsSpek.kt:10)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt$createSuite$1.invoke(specificationStyle.kt:80)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt$createSuite$1.invoke(specificationStyle.kt)
	at org.spekframework.spek2.runtime.Collector.group(Collectors.kt:57)
	at org.spekframework.spek2.dsl.GroupBody$DefaultImpls.group$default(dsl.kt:22)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.createSuite(specificationStyle.kt:79)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.describe(specificationStyle.kt:69)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.describe$default(specificationStyle.kt:68)
	at com.vanniktech.analytics.DelegateAnalyticsSpek$1.invoke(DelegateAnalyticsSpek.kt:16)
	at com.vanniktech.analytics.DelegateAnalyticsSpek$1.invoke(DelegateAnalyticsSpek.kt:10)
	at org.spekframework.spek2.runtime.SpekRuntime.resolveSpec(SpekRuntime.kt:52)
	at org.spekframework.spek2.runtime.SpekRuntime.discover(SpekRuntime.kt:23)
	at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:75)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by raniejade** [comment]
Two versions of spek in the classpath perhaps?  That's the only thing I could see that may cause that exception.

**Comment by vanniktech** [comment]
You're absolutely right. Silly me.

**Comment by vegeta2102** [comment]
@vanniktech I'm facing the same issue ? How did you solve it ?
I already tried clean, build , sync gradle many time but not fix yet ...

**Comment by vanniktech** [comment]
> Two versions of spek in the classpath perhaps? That's the only thing I could see that may cause that exception.

That

**Comment by CACuzcatlan** [comment]
@vanniktech how do I assume that there is only one version in the classpath? I converted all my tests to Spek2 and removed all references to Spek, but I still get this error.

**Comment by raniejade** [comment]
@CACuzcatlan what build tool are you using? There should be a way to print out the dependency tree. You also need the same version of spek for the IJ plugin.
