### ISSUE TITLE
Error in Intellij

### ISSUE THREAD

**Issue by Jano14** [JetBrains/spek#699]
IntelliJ return me this error:

`java.lang.NoSuchMethodError: org.jetbrains.kotlin.resolve.lazy.data.KtClassInfoUtil.createClassOrObjectInfo(Lorg/jetbrains/kotlin/psi/KtClassOrObject;)Lorg/jetbrains/kotlin/resolve/lazy/data/KtClassOrObjectInfo;
	at org.spekframework.intellij.domain.ScopeDescriptorCache.buildDescriptor(ScopeDescriptorCache.kt:50)
	at org.spekframework.intellij.domain.ScopeDescriptorCache.fromClassOrObject(ScopeDescriptorCache.kt:42)
	at org.spekframework.intellij.SpekRunLineMarkerContributor.getInfo(SpekRunLineMarkerContributor.kt:35)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

Whenever I try to run a test from IntelliJ, give me the same result: "Test Framework quit unexpectedly"

**Project Gradle Info:**
IntelliJ version: IntelliJ IDEA 2019.1.1
JRE: 1.8.0_211
Kotlin version: 1.3.31
Spek version: 2.0.4

This is my build.gradle.kts:
`import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val spekVersion = "2.0.4"

plugins {
    kotlin("jvm") version "1.3.31"
    application
}

group = "project"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    mavenLocal()
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation(kotlin("reflect"))
    implementation(kotlin("test"))
    implementation(kotlin("test-junit"))

    // Spek
    testImplementation("org.spekframework.spek2:spek-dsl-jvm:$spekVersion")
    testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:$spekVersion")

    // Mockk
    testImplementation("io.mockk:mockk:1.9")

    // Rest assured
    testCompile("io.rest-assured:rest-assured:3.1.0")

    // Hamkrest
    testCompile("com.natpryce:hamkrest:1.7.0.0")

    // AssertK
    testCompile("com.willowtreeapps.assertk:assertk-jvm:0.13")

}

application {
    mainClassName = "project.MainKt"
}

tasks.withType<Test> {
    useJUnitPlatform {
        includeEngines("spek2")
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}`

Any ideas to solve it?

Thank you!

**Comment by raniejade** [comment]
I've seen this before, you need to update kotlin IJ plugin to the latest version.

**Comment by Jano14** [comment]
Thank you for your comment @raniejade now works fine!!

**Comment by krzykrucz** [comment]
@raniejade I've got the latest version of kotlin IJ plugin and the error stil occurs. I have the same versions as Jano14

**Comment by raniejade** [comment]
@krzykrucz can you share a reproducer?

**Comment by krzykrucz** [comment]
> @krzykrucz can you share a reproducer?

I'm not sure what do you mean by a reproducer. The exception happens every time I open a file with a Spek test.

**Comment by raniejade** [comment]
Just a sample project that always replicates the issue. Just for context, the exception will only happen if you have an older version of the kotlin plugin installed. What version do you have (project and IDE plugin)?

**Comment by gaplo917** [comment]
@krzykrucz I solved by install the latest kotlin IJ plugin manually https://plugins.jetbrains.com/plugin/6954-kotlin/versions

My IntelliJ version: IntelliJ IDEA 2019.1.2. IDE shows that "kotlin IJ (1.3.21) plugin" has **NO** update. 

Manually download the plugin(1.3.31) and install from disk solve the problem.
