### ISSUE TITLE
How do you test methods that call Resources.getSystem()?

### ISSUE THREAD

**Issue by obianachebe** [JetBrains/spek#701]
I'm testing a presenter class that gets string resources from my resource directory like so:

```
fun createLogActionSheet(): ActionSheet {
    ...
    val title = Resources.getSystem().getString(R.string.title)
    return ActionSheet(title)
}
```

When called in my Spek test file using the Android Studio Plugin an exception is thrown

```
Stub!
java.lang.RuntimeException: Stub!
	at android.content.res.Resources.getSystem(Resources.java:87)
	at com.fitgenie.fitgenie.modules.log.LogPresenter.createLogActionSheet(LogPresenter.kt:170)
	at com.fitgenie.fitgenie.modules.log.LogPresenter.onActionSheetItemTap(LogPresenter.kt:362)
	at com.fitgenie.fitgenie.modules.log.LogPresenterTests$1$1$6$6.invoke(LogPresenterTests.kt:204)
	at com.fitgenie.fitgenie.modules.log.LogPresenterTests$1$1$6$6.invoke(LogPresenterTests.kt:39)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:92)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.SpekRuntime.execute(SpekRuntime.kt:33)
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:24)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)
```

I understand that the Spek plugin cannot run code that calls any Android API. Unfortunately, I don't know any other way to access my string resources. Is there any way around this besides using `gradlew test`? Thanks in advance

**Comment by raniejade** [comment]
Probably related to #667. What AS version are you using?

**Comment by obianachebe** [comment]
@raniejade thanks for the reply. See my environment below

Spek Framework: 2.0.2

Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 9, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

**Comment by raniejade** [comment]
@obianachebe from my understanding the tests passed when running in gradle but not in AS?

**Comment by obianachebe** [comment]
@raniejade my mistake. The test does not pass when running in gradle because `Resources.getSystem()` is an Android API which cannot be run in JVM. This is probably a mocking issue

**Comment by raniejade** [comment]
Right, not really a Spek problem as we don't support (yet) running tests that require the android runtime.
