### ISSUE TITLE
TestEngine with ID 'spek2' failed to discover tests

### ISSUE THREAD

**Issue by ravikumar-n** [JetBrains/spek#801]
I'm using Spek2 (`v2.0.6`) on my Android project. All my ViewModel tests extends the `BaseSpek` class.

**BaseSpek.kt**
```
open class BaseSpek(spec: Root.() -> Unit) : Spek({

    beforeGroup {
        ArchTaskExecutor.getInstance().setDelegate(object : TaskExecutor() {
            override fun executeOnDiskIO(runnable: Runnable) {
                runnable.run()
            }

            override fun isMainThread(): Boolean {
                return true
            }

            override fun postToMainThread(runnable: Runnable) {
                runnable.run()
            }
        })
    }

    afterGroup {
        afterEachTest { ArchTaskExecutor.getInstance().setDelegate(null) }
    }

    spec(this)
})
```
When I execute all these tests from Android Studio it would run properly, but when I run via commandline like below:
```
>./gradlew :moduleName:testDebug -i
```
Spek tests are skipped with below error message:
```
Gradle Test Executor 1 STANDARD_ERROR
    Oct 02, 2019 10:57:18 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'spek2' failed to discover tests
    java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at org.spekframework.spek2.runtime.JvmDiscoveryContextFactory$defaultInstanceFactory$1.create(JvmDiscoveryContextFactory.kt:63)
        at org.spekframework.spek2.runtime.JvmDiscoveryContextFactory$create$3$1.invoke(JvmDiscoveryContextFactory.kt:29)
        at org.spekframework.spek2.runtime.JvmDiscoveryContextFactory$create$3$1.invoke(JvmDiscoveryContextFactory.kt:14)
        at org.spekframework.spek2.runtime.discovery.TestInfo.createInstance(context.kt:11)
        at org.spekframework.spek2.runtime.SpekRuntime.discover(SpekRuntime.kt:24)
        at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:92)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
           at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```
But If I extend all ViewModel tests from `Spek` instead of `BaseSpek` the tests fails but at-least it's get executed on commandline. 

I want to share the common logic for all ViewModel tests using `BaseSpek`.  So what's the possible workaround for this scenario?

**Comment by raniejade** [comment]
You should use `abstract` instead of `open`. Is there a particular reason you need it `open`? If yes, you can use `@Ignore` so Spek won't try to instantiate the base class.

**Comment by ravikumar-n** [comment]
@raniejade The class doesn't need to be `open`, changing it to `abstract` solved the issue. 

There should be some kind of warning/error message when `Spek` tests are ignored when it is not annotated with `@Ignore`. Because of the above issue, my module with 5+ normal test classes(which just extends `Spek`) containing 20+ tests in were entirely ignored. Upon watching `Jacoco` code coverage report only I found out the issue. 

Shouldn't the behavior between Spek runner plugin in IDE and `gradle` commandline be the same?  If Spek IDE plugin had warned about the ignore issue, I might have easily identified the problem and fixed it.

**Comment by raniejade** [comment]
I've opened #806, closing this for now. I'm also going to upgrade to the latest JUnit Platform, from what I remember it now reports discovery failures properly instead of silently ignoring them.
