### ISSUE TITLE
Allow disabling timeout in IJ globally

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#847]
See #846.

**Comment by asubb** [comment]
As a manual but one-time fix is to populate `-DSPEK_TIMEOUT=0` in the VM Options field of the Spek2 configuration template (i.e. `Run/Debug Configurations > Templates > Spek 2 - JVM`) . That'll work for every new run/debug configuration.

Btw the exception is very misleading, I spent whole day thinking my code failing so weirdly as it also uses coroutines. It fails in some separate thread without referring to actual owner:

```
Timed out waiting for 10000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:116)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:86)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:493)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by raniejade** [comment]
Thanks for the report @asubb, in the next patch release timeouts are now disabled by default. With regards with the stacktrace, I can't think of a way to fix it at the moment - do you have any suggestions?

**Comment by asubb** [comment]
Honestly didn't look into code. Though may tell that this timeout works quite interesting. It wasn't interrupting the execution of my code, but instead was failing just when my code has finished successfully, as it took longer than container expected. 

And of course I didn't expect my code would be launched in something different from main thread.

As from my past experience, I've tried using timeouts in JUnit 4 on some old code which was using ThreadLocal. Test container launches the test in a separate thread. Obviously it didn't work out well. Why I'm telling this, perhaps launching the test in the coroutine/thread different from the main one, may cause quite interesting sides effect which would be hard to overcome.

My example, probably, is not fully correct, as there is quite a mix of multithreaded processing was involved. Eventually I got rid of coroutines as they were just coming from one of the libraries and were not used directly.

**Comment by raniejade** [comment]
I'll probably wrap the exception into something more meaningful, i.e in the exception message include which test failed.

**Comment by raniejade** [comment]
Another improvement here is disabling timeouts when running a debugging a test in intellij. I think it is doable with JVM but I'm not sure how to implement it in other platforms.
