### ISSUE TITLE
More output in spek-runner-junit5

### ISSUE THREAD

**Issue by JWT007** [JetBrains/spek#862]
Currently when running via Maven with a Spek Test I only see something like the following in the console output (SomeSpek test is in Gherkin style):

    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running SomeSpek
    [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.122 s - in SomeSpek
    [INFO] 
    [INFO] Results:
    [INFO] 
    [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

If possible, I would like to see something more like the Cucumber example:

    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running hellocucumber.RunCucumberTest
    Feature: Is it Friday yet?
      Everybody wants to know when it's Friday
      Scenario: Sunday isn't Friday        # hellocucumber/is_it_friday_yet.feature:4
        Given today is Sunday              # null
        When I ask whether it's Friday yet # null
        Then I should be told "Nope"       # null
           java.lang.AssertionError: expected:<Nope> but was:<null>
             at org.junit.Assert.fail(Assert.java:88)
             at org.junit.Assert.failNotEquals(Assert.java:834)
             at org.junit.Assert.assertEquals(Assert.java:118)
             at org.junit.Assert.assertEquals(Assert.java:144)
             at hellocucumber.Stepdefs.i_should_be_told(Stepdefs.java:31)
             at ?.I should be told "Nope"(classpath:hellocucumber/is_it_friday_yet.feature:7)
    
    Failed scenarios:
    hellocucumber/is_it_friday_yet.feature:4 # Sunday isn't Friday
    
    1 Scenarios (1 failed)
    3 Steps (1 failed, 2 passed)
    0m0.404s

**Comment by raniejade** [comment]
Definitely something that can be improved, however at the moment spek relies on the reporting infastructure your build tool provides.

**Comment by corlaez** [comment]
I would also love to see an improvement on console output as it seems only the IDE is able to show the describe context information
```kt
object CalculatorSpec: Spek({
    describe("A calculator") {
        describe("addition") {
            it("returns the sum of its arguments") {
                assertEquals(3, 2)
            }
        }
    }
})
```
`./gradlew test` Results in:
```
> Task :test

CalculatorSpec > returns the sum of its arguments FAILED
    java.lang.AssertionError at AppTest.kt:11
        Caused by: java.lang.AssertionError at AppTest.kt:11

1 test completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/armando/Documents/github/millones/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 1 executed, 3 up-to-date
```
As you can see the "A calculator" and "addition" information are not shown.

**Comment by JWT007** [comment]
going through open tickets submitted by me - this ticket hasn't had any attention since 2020.

I personally haven't been any to play with Kotlin for years now?

Maintainers - close?
