### ISSUE TITLE
Android Studio 4 and mockito-android Crash

### ISSUE THREAD

**Issue by danielgomezrico** [JetBrains/spek#887]
# Env
Using:
- Spek "2.0.10" and "2.0.11".
- Spek plugin: "2.0.11-IJ2019.3".
- mockito 3.3.3:
    * `androidTestImplementation "org.mockito:mockito-android:$mockito"`
    * `testImplementation "org.mockito:mockito-core:$mockito"`

- Android Studio 4.0
- kotlin 1.3.72.

# Description

Having `androidTestImplementation "org.mockito:mockito-android:$mockito"` in gradle causes the unit test (which is not what androidTestImplementation is intended for) to fail when I call mock function I get an error on MockMaker:

> This only happens when I run the tests from Android Studio and not from the terminal with `./gradlew testDebugUnitTest`.

```kotlin
Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy2.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:241)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:229)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1908)
...
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@66c94af4
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:22)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:19)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	... 30 more
Caused by: java.lang.NullPointerException
	at org.mockito.internal.configuration.plugins.Plugins.getMockitoLogger(Plugins.java:66)
	at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.<init>(AndroidByteBuddyMockMaker.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
	... 35 more
```

I need to mock objects in my Instrumentation Tests also, so I need this dependency.

What can I do?

**Comment by danielgomezrico** [comment]
Im not sure if this is a bug related to spek itself or to mockito https://github.com/mockito/mockito/issues/1944.

**Comment by raniejade** [comment]
I can't say from the stacktrace if spek is causing it, probably wait for someone in the mockito team to comment at https://github.com/mockito/mockito/issues/1944.

**Comment by danielgomezrico** [comment]
Yeah, Im not sure, the weird thing is that it only crashes when I run an `spek` test from android studio. 

They runs fine if :
- I run them from the terminal with: `./gradlew testDebugUnitTest`
- I run another test that does not involve spek from android studio.

That's what makes me think that maybe comes from spek somehow.

**Comment by danielgomezrico** [comment]
After updating the Android Build Tools to version 30 mockito does not crash anymore.

To be honest I don't understand why that fixed it.
